# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solarvent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proizvod_dimanzija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tezina', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='kg')),
                ('duzina', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='mm')),
                ('sirina', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='mm')),
                ('visina', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='mm')),
                ('max_snaga', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='W')),
            ],
        ),
        migrations.CreateModel(
            name='Proizvod_main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proizvod', models.CharField(max_length=128, verbose_name='Naziv proizvoda')),
            ],
            options={
                'ordering': ['proizvod'],
            },
        ),
        migrations.CreateModel(
            name='Proizvod_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_detalj', models.CharField(max_length=32, verbose_name='Model detalj')),
            ],
            options={
                'ordering': ['model_detalj'],
            },
        ),
        migrations.CreateModel(
            name='Proizvod_opis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(max_length=128, verbose_name='Opis proizvoda')),
                ('model', models.CharField(max_length=128, verbose_name='Model')),
                ('proizvod_main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarvent.Proizvod_main')),
            ],
            options={
                'ordering': ['opis'],
            },
        ),
        migrations.CreateModel(
            name='Proizvod_rezim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rezim_opis', models.CharField(max_length=128, verbose_name='Naziv re\u017eima')),
                ('proizvod_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarvent.Proizvod_model')),
            ],
        ),
        migrations.CreateModel(
            name='Rezim_det',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brzina', models.DecimalField(decimal_places=4, max_digits=14)),
                ('voda_ulaz', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='EWT\xb0C')),
                ('voda_izlaz', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='LWT\xb0C')),
                ('voda_protok', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='l/s')),
                ('voda_pad_tlaka', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='kPa')),
                ('zrak_protok', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='m3/h')),
                ('rash_ucin', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='W')),
                ('osjetni_ucin', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='W')),
                ('zrak_izlaz', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='LAT\xb0C')),
                ('zvucni_tlak', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='dB(A)')),
                ('zvucna_snaga', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='dB(A)')),
                ('ucin_grijanja', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='W')),
                ('el_snaga', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='W')),
                ('proizvod_rezim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarvent.Proizvod_rezim')),
            ],
        ),
        migrations.AlterModelOptions(
            name='proizvodjac',
            options={'ordering': ['naziv']},
        ),
        migrations.AlterField(
            model_name='proizvodjac',
            name='naziv',
            field=models.CharField(max_length=128, verbose_name='Naziv proizvo\u0111a\u010da'),
        ),
        migrations.AddField(
            model_name='proizvod_opis',
            name='proizvodjac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarvent.Proizvodjac'),
        ),
        migrations.AddField(
            model_name='proizvod_model',
            name='proizvod_opis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarvent.Proizvod_opis'),
        ),
        migrations.AddField(
            model_name='proizvod_dimanzija',
            name='proizvod_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarvent.Proizvod_model'),
        ),
    ]
