# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 14:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solarvent', '0002_auto_20170515_1611'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proizvod_dimanzija',
            new_name='Proizvod_dimenzija',
        ),
    ]
