# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarvent', '0003_auto_20170515_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezim_det',
            name='osjetni_ucin',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='W'),
        ),
        migrations.AlterField(
            model_name='rezim_det',
            name='rash_ucin',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='W'),
        ),
        migrations.AlterField(
            model_name='rezim_det',
            name='ucin_grijanja',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='W'),
        ),
    ]
