# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarvent', '0004_auto_20170515_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezim_det',
            name='brzina',
            field=models.CharField(max_length=64),
        ),
    ]
